name: Build, Push, and Deploy to ECS/Fargate
on:
  workflow_dispatch: 
jobs:
  build-and-push-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [appointmentapp, patient-app]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-cli@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Authenticate Docker with ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 539935451710.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and Push Docker Image to ECR
        run: |
          docker build -t 539935451710.dkr.ecr.us-east-1.amazonaws.com/hcl_ecr_repo:${{ matrix.service }} ./{{ matrix.service }}
          docker tag 539935451710.dkr.ecr.us-east-1.amazonaws.com/hcl_ecr_repo:${{ matrix.service }} 539935451710.dkr.ecr.ecr.us-east-1.amazonaws.com/hcl_ecr_repo:${{ matrix.service }}:latest
          docker push 539935451710.dkr.ecr.us-east-1.amazonaws.com/hcl_ecr_repo:${{ matrix.service }}
          docker push 539935451710.dkr.ecr.us-east-1.amazonaws.com/hcl_ecr_repo:${{ matrix.service }}:latest

      - name: Deploy to ECS/Fargate
        run: |
          aws ecs update-service \
            --cluster hcl_ecs_cluster \
            --service ${{ matrix.service }}-service \
            --force-new-deployment